# Importaci√≥n de Librerias

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report, confusion_matrix

# Cargue de los datos

In [6]:
Cartera_activa = pd.read_csv('C:\\Users\\IVAN.LIPES\\Documents\\Alafecha\\Clustering\\INFORME_CARTERA_15112024.csv', sep=";")

C:\Users\IVAN.LIPES\AppData\Local\Temp\ipykernel_3016\2478596875.py:1: DtypeWarning: Columns (5,8,15,54,57,61,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  Cartera_activa = pd.read_csv('C:\\Users\\IVAN.LIPES\\Documents\\Alafecha\\Clustering\\INFORME_CARTERA_15112024.csv', sep=";")

In [7]:
Cartera_activa

,Consecutivo,Numero De Obligacion,Documento Cliente,Nombre Cliente,Saldo Capital,Estado De Cobro Visita,Numero De Cuotas,Fecha Actualizacion,Fecha Ult Gestion Visita,Estado,...,Ultimo Externo,Gestion Directa Codeudor,Canal Gestion Directa Codeudor,Gestion En Semana,Causal,Tarea Del Usuario,Usuario,Grabador,Estado De Cobro,Ultima Gestion Unificada
0,883798,402911602288,148394,OSCAR ABUCHAIBE CASSIS,545365.0,NaN,1,2024-11-15,2022-02-24,A,...,goech,NO,NO,NO,NO CONOCEN AL CLIENTE,NaN,NaN,jguarguati,COBRO ADMINISTRATIVO,4001
1,883799,101910487392,353318,KENNEDY PASCUAL REYNOSO,498108.0,NaN,1,2024-11-15,2022-02-24,A,...,goech,NO,NO,NO,NO VIVE EN ESE TELEFONO DE CONTACTO,NaN,NaN,dalvarado,COBRO ADMINISTRATIVO,4001
2,883800,201101011356,479632,ALIRIO ALFONSO MOLINA ROA,444776.0,VISITA NO EFECTIVA,1,2024-11-15,2011-09-07,A,...,goech,NO,NO,NO,NaN,NaN,NaN,jguarguati,COBRO ADMINISTRATIVO,4001
3,883801,201101011357,479632,ALIRIO ALFONSO MOLINA ROA,232617.0,VISITA NO EFECTIVA,1,2024-11-15,2011-09-07,A,...,goech,NO,NO,NO,NaN,NaN,NaN,jguarguati,COBRO ADMINISTRATIVO,4001
4,883804,302911327611,822180,RAMON SANCHEZ ALVAREZ,210048.0,NaN,1,2024-11-15,NaN,A,...,goech,NO,NO,NO,NO CONOCEN AL CLIENTE,NaN,NaN,jguarguati,COBRO ADMINISTRATIVO,4001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404226,1886710,531181007346471,92097608,JOSE BENITO AVILA ROMERO,3702513.0,NaN,1,2024-11-15,NaN,A,...,NaN,NO,NO,NO,NaN,NaN,NaN,admon,CARTERA PARA COBRO (AUTOMATICO),9999
404227,1886711,133232020131,9536202,FABIAN HUMBERTO TORRES CASALLAS,23076.0,NaN,12,2024-11-15,NaN,A,...,NaN,NO,NO,NO,NaN,NaN,NaN,admon,CARTERA PARA COBRO (AUTOMATICO),9999
404228,1886712,822221012822,94479151,CRISTHIAN FABIAN ROJAS CRUZ,1430475.0,NaN,24,2024-11-15,NaN,A,...,NaN,NO,NO,NO,NaN,NaN,NaN,admon,CARTERA PARA COBRO (AUTOMATICO),9999
404229,1886713,817232014775,98137848,JESUS HERNAN ESTRADA VILLOTA,366189.0,NaN,18,2024-11-15,NaN,A,...,NaN,NO,NO,NO,NaN,NaN,NaN,admon,CARTERA PARA COBRO (AUTOMATICO),9999
404230,1886714,610231017326,98538378,CARLOS MARIO URIBE GOMEZ,3872839.0,NaN,36,2024-11-15,NaN,A,...,NaN,NO,NO,NO,NaN,NaN,NaN,admon,CARTERA PARA COBRO (AUTOMATICO),9999

In [9]:
df_cruces=Cartera_activa[['Numero De Obligacion','Documento Cliente']]

In [10]:
df_cruces

        Numero De Obligacion  Documento Cliente
0               402911602288             148394
1               101910487392             353318
2               201101011356             479632
3               201101011357             479632
4               302911327611             822180
...                      ...                ...
404226       531181007346471           92097608
404227          133232020131            9536202
404228          822221012822           94479151
404229          817232014775           98137848
404230          610231017326           98538378

[404231 rows x 2 columns]

In [12]:
df_cruces.to_csv('C:\\Users\\IVAN.LIPES\\Documents\\Alafecha\\Casas_de_cobro\\Cartera_2024.csv')